#!/bin/sh

# mpick msgs... | mapply cmd     # pipes each msg into cmd
# mpick msgs... | mapply -a cmd  # runs cmd $filename on each msg

as_args=0
[ "$1"  = "-a" ] && {
	as_args=1
	shift
}
while read filename; do
	if [ $as_args -eq 0 ]; then
		[ -f ${filename} ] && eval "$*" < $filename
	else
		eval "$* ${filename}"
	fi
done
