#!/bin/ksh

# minbox - list some inbox 

MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
inbox_name=$(mhdr -h InboxName "$MBLAZE/profile")
[ -z "${inbox_name}" ] && inbox_name=INBOX
inbox=$(mhdr -h Inbox "$MBLAZE/profile")
[ -z "${inbox}" ] && inbox=${basedir}/${inbox_name}
scanner=mscan
sequence="mseq -S"
[ -n "$MB_PURTY" ] && {
	sequence=mseq
	scanner="mapply msummary"
}
threader=mthread
verbose=0

while [ $# -ne 0 ]; do
	case "$1" in
		-v) verbose=$(expr 1 + $verbose); shift ;;
		-t) threader=cat; shift ;;
		*) break ;;
	esac
done
if [ $# -gt 0 ]; then
	inbox="${basedir}/$1"
	shift
fi
mlist_args="$*"
filter=cat
if [ -n "$MB_HEAD" ]; then
	filter="head -$MB_HEAD"
elif [ -n "$MB_TAIL" ]; then
	filter="tail $MB_TAIL"
elif [ -n "$MB_MID" ]; then
	sedexp=$(echo $MB_MID | sed -e 's/-/,/')
	filter="sed -n -e ${sedexp}p"
fi
[ $verbose -ne 0 ] &&
	echo ">> mlist ${mlist_args} ${inbox} | ${filter} | ${threader} | ${sequence} | ${scanner}" 1>&2
mlist ${mlist_args} ${inbox} | ${filter} | ${threader} | ${sequence} | ${scanner}
