#!/bin/sh
# list some inbox 
MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
inbox=$(mhdr -h Inbox "$MBLAZE/profile")
inbox=${inbox-${basedir}/INBOX}
[ -n "$1" ] && {
	if [ -d "$1" ]; then
		inbox="$1"
	else
		inbox="${basedir}/$1"
	fi
	shift
}
mlist_args="$*"
mlist ${mlist_args} ${inbox} | mthread | mseq -S | mscan
