#!/bin/sh

# mcp [msg#...] dst-maildir
# mmv [msg#...] dst-maildir

# If dst-maildir doesn't end in /new and adding /new makes it a valid
# directory we append /new

# We look in ~/.mblaze/profile for MaildirBase

MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}

# collect varname ...
collect () {
	typeset var val
	var=$1
	shift
	for arg in $*; do
		val=$(eval '$'$var)
		if [ -z "$val" ]; then
			val=$arg
		else
			val="${val} ${arg}"
		fi
		eval $var="$val"
	done
}

mvcp=cp
case "$0" in
	*mv) mvcp=mv ;;
	*cp) mvcp=cp ;;
	*)
		echo $0: what am i supposed to be'?'
		exit 1 ;;
esac

[ $# -eq 0 ] && {
	echo "usage: ${SCRIPT} [msgs...] dest-folder"
	echo "    if no messages are specified they are assumed on stdin"
	exit 1
}

msgs=""
while [ $# -gt 1 ]; do
	typeset m
	m=$1
	shift
	collect msgs $m
done

dst=$1
shift
[ ! -d ${dst} ] && dst="${basedir}/${dst}"
case "$dst" in
	*/new) ;;
	*/cur) ;;
	*) [ -d "${dst}/new" ] && dst="${dst}/new" ;;
esac
[ ! -d ${dst} ] && {
	echo "$0: destination not a directory: ${dst}"
	exit 1
}

input_cmd=cat
[ -n "$msgs" ] && {
	inputs=""
	for picker in ${msgs}; do
		collect inputs $(mpick ${picker} 2>/dev/null)
	done
	input_cmd="echo ${inputs}"
}

eval "${input_cmd}" | while read filename; do
	[ -f ${filename} ] && ${mvcp} ${filename} ${dst} && \
		echo ${dst}/$(basename ${filename})
done
