#!/bin/ksh

# mnewbox - list only new mail in maildir

MBLAZE=${MBLAZE-$HOME/.mblaze}

cfglook () {
	mhdr -h $* | envsubst
}

inbox_name=$(cfglook InboxName "$MBLAZE/profile")
[ -z "${inbox_name}" ] && inbox_name=INBOX

if [ $# -eq 0 ]; then
	box=$inbox_name
else
	box="$1"
	shift
fi
echo '** '$box >& 2
minbox ${box} -N $*
