#!/bin/sh

# mnewbox - list only new mail in maildir

MBLAZE=${MBLAZE-$HOME/.mblaze}
inbox_name=$(mhdr -h InboxName "$MBLAZE/profile")
[ -z "${inbox_name}" ] && inbox_name=INBOX

if [ $# -eq 0 ]; then
	box=$inbox_name
else
	box="$1"
	shift
fi
echo '** '$box >& 2
minbox ${box} -N $*
