#!/bin/sh

# mpane [-nh] [-mloop_options] [cmd_args]

# set MpaneLines in ~/.mblaze/profile to change
# the default size of the pane we create in tmux

MBLAZE=${MBLAZE-${HOME}/.mblaze}

# collect varname ...
collect () {
	typeset var val
	var=$1
	shift
	for arg in $*; do
		val=$(eval '$'$var)
		if [ -z "$val" ]; then
			val=$arg
		else
			val="${val} ${arg}"
		fi
		eval $var="$val"
	done
}

horiz=
args=
cmd=minbox
opts=
arg0=

for arg in $*; do
	case $arg in
		-n)	cmd=mnewbox ;;
		-h)	horiz=-h ;;
		-*)	collect opts ${arg} ;;
		*)	[ -z "${arg0}" ] && arg0=${arg}
			collect args ${arg} ;;
	esac
done

lines=$(mhdr -h MpaneLines "$MBLAZE/profile")
[ -z "$lines" ] && lines=20
tmux split-window ${horiz} -l ${lines} "${cmd} ${args}; env CMD=${cmd} FOLDER=${arg0} mloop ${opts}"
