#!/bin/sh

# mrespam - mark a message as spam and move it to Spam

MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
spamdir=${SPAMDIR-${basedir}/Spam}
bmf_flags=-S

respamify () {
	typeset filename name spamf
	while read filename; do
		name=$(basename $filename)
		spamf=${spamdir}/new/${name}
		bmf ${bmf_flags} -p < ${filename} | tee ${spamf} | msummary
		rm ${filename}
	done
}

if [ -z "$*" ]; then
	respamify
else
	for picker in $*; do
		mpick ${picker} | respamify
	done
fi
