#!/bin/ksh

# mrespam - mark a message as spam and move it to Spam

MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
spamdir=${SPAMDIR-${basedir}/Spam}
bmf=$(mhdr -h BayesianCmd "$MBLAZE/profile")
[ -z "$bmf" ] && bmf=bmf
re_flags=$(mhdr -h BayesianRespamFlags "$MBLAZE/profile")
[ -z "$re_flags" ] && re_flags=-N
sp_flags=$(mhdr -h BayesianSpamFlags "$MBLAZE/profile")
[ -z "$sp_flags" ] && sp_flags=-s
bmf_flags=${sp_flags}

args=$(getopt Rv $*)
if [ $? -ne 0 ]; then
	echo "usage: $(basename $0) [-Rv] [msg...]"
	exit 1
fi
set -- $args
while [ $# -ne 0 ]; do
	case "$1" in
		-v) bmf="${bmf} -v"; shift ;;
		-R) bmf_flags=${re_flags} ; shift ;;
		--)  shift; break ;;
	esac
done

respamify () {
	typeset filename name spamf
	while read filename; do
		name=$(basename $filename)
		spamf=${spamdir}/new/${name}
		${bmf} ${bmf_flags} -p < ${filename} | tee ${spamf} | msummary
		rm ${filename}
	done
}

if [ -z "$*" ]; then
	respamify
else
	for picker in $*; do
		mpick ${picker} | respamify
	done
fi
