#!/bin/sh

# munspam - unmark a message as spam and put it back in INBOX

MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
inbox_name=$(mhdr -h InboxName "$MBLAZE/profile")
[ -z "${inbox_name}" ] && inbox_name=INBOX
inbox=$(mhdr -h Inbox "$MBLAZE/profile")
[ -z "${inbox}" ] && inbox=${basedir}/${inbox_name}
bmf_flags=-N

unspamify () {
	typeset filename name okf
	while read filename; do
		name=$(basename $filename)
		okf=${inbox}/new/${name}
		bmf ${bmf_flags} -p < ${filename} | tee ${okf} | msummary
		rm ${filename}
	done
}

if [ -z "$*" ]; then
	unspamify
else
	for picker in $*; do
		mpick ${picker} | unspamify
	done
fi
