#!/bin/sh

# munspam - unmark a message as spam and put it back in INBOX
MBLAZE=${MBLAZE-$HOME/.mblaze}
basedir=$(mhdr -h MaildirBase "$MBLAZE/profile")
basedir=${basedir-$HOME/Maildir}
inbox=$(mhdr -h Inbox "$MBLAZE/profile")
inbox=${inbox-${basedir}/INBOX}
bmf_flags=-N

unspamify () {
	typedef filename name okf
	while read filename; do
		name=$(basename $filename)
		okf=${inbox}/new/${name}
		bmf ${bmf_flags} -p < ${filename} | tee ${okf} | msummary
		rm ${filename}
	done
}

if [ -z "$*" ]; then
	unspamify
else
	for picker in $*; do
		mpick ${picker} | unspamify
	done
fi
